/* 
 * The lists of props options for open peeps avatar:
 * https://github.com/CeamKrier/react-peeps
 */

import { random, sample } from 'lodash';

export const accessories = [
  'None',
  'Eyepatch',
  'GlassRoundThick',
  'SunglassClubmaster',
  'SunglassWayfarer',
  'GlassAviator',
  'GlassButterfly',
  'GlassButterflyOutline',
  'GlassClubmaster',
  'GlassRound',
];

export const faces = [
  'Angry',
  'Blank',
  'Calm',
  'Cheeky',
  'Concerned',
  'Contempt',
  'Cute',
  'Driven',
  'EatingHappy',
  'EyesClosed',
  'OldAged',
  'Serious',
  'Smile',
  'Solemn',
  'Suspicious',
  'Tired',
  'VeryAngry',
  'Awe',
  'ConcernedFear',
  'Cyclops',
  'Explaining',
  'Fear',
  'Hectic',
  'LoveGrin',
  'LoveGrinTeeth',
  'Monster',
  'Rage',
  'SmileBig',
  'SmileLol',
  'SmileTeeth',
  'CalmNM',
  'SmileNM',
  'CheersNM',
];

export const facialHairStyles = [
  'None',
  'Chin',
  'Full',
  'FullMajestic',
  'FullMedium',
  'Goatee',
  'GoateeCircle',
  'Dali',
  'Handlebars',
  'Imperial',
  'Painters',
  'PaintersFilled',
  'Swashbuckler',
  'MoustacheThin',
  'Yosemite',
  'GrayFull',
  'MajesticHandlebars',
];

export const hairStyles = [
  'Afro',
  'Bald',
  'BaldSides',
  'BaldTop',
  'Bangs',
  'BangsFilled',
  'Bear',
  'Bun',
  'BunCurly',
  'Buns',
  'FlatTop',
  'FlatTopLong',
  'HatHip',
  'Long',
  'LongAfro',
  'LongBangs',
  'LongCurly',
  'Medium',
  'MediumBangs',
  'MediumBangsFilled',
  'MediumLong',
  'MediumShort',
  'MediumStraight',
  'Mohawk',
  'MohawkDino',
  'Pomp',
  'ShavedRight',
  'ShavedSides',
  'ShavedWavy',
  'Short',
  'ShortCurly',
  'ShortMessy',
  'ShortScratch',
  'ShortVolumed',
  'ShortWavy',
  'BantuKnots',
  'Beanie',
  'BunFancy',
  'CornRows',
  'CornRowsFilled',
  'GrayBun',
  'GrayMedium',
  'GrayShort',
  'Hijab',
  'MediumShade',
  'Turban',
  'Twists',
  'TwistsVolumed',
  'DocBouffant',
  'DocSurgery',
  'DocShield',
];

export const bustPoses = [
  'BlazerBlackTee',
  'Shirt',
  'ButtonShirt',
  'Dress',
  'Gaming',
  'Geek',
  'Hoodie',
  'PointingUp',
  'Selena',
  'Thunder',
  'Turtleneck',
  'ArmsCrossed',
  'Coffee',
  'Device',
  'DotJacket',
  'Explaining',
  'FurJacket',
  'Killer',
  'Paper',
  'PocketShirt',
  'PoloSweater',
  'ShirtCoat',
  'ShirtFilled',
  'SportyShirt',
  'StripedShirt',
  'Sweater',
  'SweaterDots',
  'Whatever',
];

export const sittingPoses = [
  'Bike',
  'ClosedLegBW',
  'ClosedLegWB',
  'CrossedLegs',
  'HandsBackBW',
  'HandsBackWB',
  'MediumBW',
  'MediumWB',
  'OneLegUpBW',
  'OneLegUpWB',
  'WheelChair',
];

export const standingPoses = [
  'BlazerBW',
  'BlazerPantsBW',
  'BlazerPantsWB',
  'BlazerWB',
  'CrossedArmsBW',
  'CrossedArmsWB',
  'EasingBW',
  'EasingWB',
  'PointingFingerBW',
  'PointingFingerWB',
  'PolkaDots',
  'RestingBW',
  'RestingWB',
  'RoboDanceBW',
  'RoboDanceOutline',
  'RoboDanceWB',
  'ShirtBW',
  'ShirtPantsBW',
  'ShirtPantsWB',
  'ShirtWB',
  'WalkingBW',
  'WalkingFilled',
  'WalkingWB',
  'Doc',
  'DocProtectiveClothe',
  'DocStethoscope',
];

export const generateRandomOpenPeepsAvatar = () => {
  const accessory = random() ? sample(accessories) : 'None';
  const facialHair = random() ? sample(facialHairStyles) : 'None';
  const flip = !!random();
  const backgroundColorIndex = random(0, 1, true);

  const face = sample(faces);
  const hair = sample(hairStyles);
  const body = sample(bustPoses);

  return {
    accessory,
    body,
    face,
    hair,
    facialHair,
    backgroundColorIndex,
    flip,
  };
};

export const validateAvatarData = (data) => ({
    ...data,
    accessory: data.accessory && accessories.includes(data.accessory) || '',
    body: data.body && bustPoses.includes(data.body) || '',
    face: data.face && faces.includes(data.face) || '',
    hair: data.hair && hairStyles.includes(data.hair) || '',
    facialHair: data.facialHair && facialHairStyles.includes(data.facialHair) || '',
  })